module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        app: {
          bg: 'var(--bg)',
          surface: 'var(--surface)',
          'surface-2': 'var(--surface-2)',
          'surface-3': 'var(--surface-3)',
          border: 'var(--border)',
          'border-strong': 'var(--border-strong)',
          text: 'var(--text)',
          muted: 'var(--muted)',
          dim: 'var(--dim)',
          cyan: 'var(--cyan)',
          'cyan-ink': 'var(--cyan-ink)',
          'cyan-soft': 'var(--cyan-soft)',
          violet: 'var(--violet)',
          green: 'var(--green)',
        },
        primary: {
          50: 'var(--cyan-soft)',
          100: 'var(--cyan-soft)',
          200: 'var(--cyan)',
          300: 'var(--cyan)',
          400: 'var(--cyan)',
          500: 'var(--cyan)',
          600: 'var(--cyan)',
          700: 'var(--cyan)',
          800: 'var(--cyan)',
          900: 'var(--cyan)',
        },
      },
      backgroundColor: {
        white: 'var(--surface)',
        slate: {
          50: 'var(--surface-3)',
          100: 'var(--surface-2)',
          200: 'var(--surface-3)',
          300: 'var(--surface-3)',
          400: 'var(--surface-3)',
          500: 'var(--surface-2)',
          600: 'var(--surface-2)',
          700: 'var(--surface-2)',
          800: 'var(--surface-2)',
          900: 'var(--surface)',
          950: 'var(--bg)',
        },
      },
      textColor: {
        slate: {
          50: 'var(--muted)',
          100: 'var(--text)',
          200: 'var(--text)',
          300: 'var(--muted)',
          400: 'var(--muted)',
          500: 'var(--muted)',
          600: 'var(--muted)',
          700: 'var(--text)',
          800: 'var(--text)',
          900: 'var(--text)',
          950: 'var(--text)',
        },
      },
      borderColor: {
        slate: {
          50: 'var(--border)',
          100: 'var(--border)',
          200: 'var(--border)',
          300: 'var(--border-strong)',
          400: 'var(--border-strong)',
          500: 'var(--border-strong)',
          600: 'var(--border-strong)',
          700: 'var(--border-strong)',
          800: 'var(--border)',
          900: 'var(--border)',
          950: 'var(--border)',
        },
      },
      ringColor: {
        slate: {
          50: 'var(--border)',
          100: 'var(--border)',
          200: 'var(--border)',
          300: 'var(--border-strong)',
          400: 'var(--border-strong)',
          500: 'var(--border-strong)',
          600: 'var(--border-strong)',
          700: 'var(--border-strong)',
          800: 'var(--border)',
          900: 'var(--border)',
          950: 'var(--border)',
        },
      },
      fontFamily: {
        sans: ['Manrope', 'ui-sans-serif', 'system-ui'],
        mono: ['DM Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      }
    }
  },
  plugins: [],
}
